// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagc38jqqi1wdYKIHCCIK9qEjlbAYPqVU',
    appId: '1:119229290655:web:e48212a76a76735f912aaa',
    messagingSenderId: '119229290655',
    projectId: 'g-d-college',
    authDomain: 'g-d-college.firebaseapp.com',
    databaseURL: 'https://g-d-college.firebaseio.com',
    storageBucket: 'g-d-college.appspot.com',
    measurementId: 'G-MBJCSW2V3D',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBagc38jqqi1wdYKIHCCIK9qEjlbAYPqVU',
    appId: '1:119229290655:web:e48212a76a76735f912aaa',
    messagingSenderId: '119229290655',
    projectId: 'g-d-college',
    authDomain: 'g-d-college.firebaseapp.com',
    databaseURL: 'https://g-d-college.firebaseio.com',
    storageBucket: 'g-d-college.appspot.com',
    measurementId: 'G-MBJCSW2V3D',
  );

}